-- Historical two-source pilot fixture. The complete catalogue is generated by
-- scripts/generate_bted_d1.py; this small seed only keeps the prototype's
-- dependency-free SQLite regression useful and is not a release seed.
INSERT INTO release_versions (
  release_version, status, is_current, release_date, canonical_manifest_path,
  canonical_manifest_sha256, asset_origin_status, materializer_version
) VALUES (
  'v0.2.0', 'preview', 1, '2026-08-22', 'release_manifest.json',
  'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'verified', 'pilot'
);

INSERT INTO publications (pmid, doi, pmc, published_year, journal, paper_title, citation_json) VALUES
('31555254', NULL, NULL, 2019, 'Example Journal', 'The Transcription Unit Architecture of Streptomyces lividans TK24', '{}'),
('33319794', NULL, NULL, 2020, 'Example Journal', 'Genome-scale determination of 5′ and 3′ boundaries in Streptomyces genomes', '{}');

INSERT INTO assemblies (
  release_version, accession, assembly_name, organism_name, strain, taxon_id, reference_url
) VALUES (
  'v0.2.0', 'GCF_000739105.1', 'Streptomyces lividans TK24', 'Streptomyces lividans',
  'TK24', NULL, 'https://example.org/GCF_000739105.1'
);

INSERT INTO contigs (
  release_version, assembly_accession, contig_accession, contig_name, length_bp,
  sequence_sha256, provenance_json
) VALUES (
  'v0.2.0', 'GCF_000739105.1', 'CP009124.1', 'CP009124.1', 8345283,
  'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', '{}'
);

INSERT INTO sources (
  release_version, source_id, assembly_accession, publication_pmid, species, phylum,
  assay_family, evidence_class, release_status, record_count, used_for_batter_augmentation,
  has_jbrowse, accessibility_status, coordinate_status, processing_status,
  redistribution_status, manifest_path, manifest_sha256, record_root, source_note,
  decision_note, known_limitations
) VALUES
('v0.2.0', 'BATTER_S1_007', 'GCF_000739105.1', '31555254', 'Streptomyces lividans', 'Actinomycetota', 'termseq', 'author_called_endpoint', 'published_standardized', 1640, 1, 1, 'public', 'verified', 'published', 'verified_redistributable', 'records/BATTER_S1_007/manifest.json', 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc', 'records/BATTER_S1_007', 'pilot', 'pilot', 'not a functional validation claim'),
('v0.2.0', 'BATTER_S1_013', 'GCF_000739105.1', '33319794', 'Streptomyces lividans', 'Actinomycetota', 'termseq', 'author_called_endpoint', 'published_standardized', 1208, 1, 1, 'public', 'verified', 'published', 'verified_redistributable', 'records/BATTER_S1_013/manifest.json', 'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', 'records/BATTER_S1_013', 'pilot', 'pilot', 'not a functional validation claim');

INSERT INTO assets (
  asset_key, release_version, assembly_accession, source_id, asset_kind, logical_path,
  origin_url, origin_host, content_type, byte_size, sha256, supports_range,
  redistribution_status, is_public, active
) VALUES
('GCF_000739105.1/reference/reference.fna', 'v0.2.0', 'GCF_000739105.1', NULL, 'fasta', 'assemblies/GCF_000739105.1/reference/reference.fna', 'https://example.org/assemblies/GCF_000739105.1/reference/reference.fna', 'example.org', 'text/plain', 8484410, '14f117887bc4c29f9336aef4b8ace10fef9cec66a92d37076c396b4aff8017af', 1, 'verified_redistributable', 1, 1),
('GCF_000739105.1/reference/reference.fna.fai', 'v0.2.0', 'GCF_000739105.1', NULL, 'fai', 'assemblies/GCF_000739105.1/reference/reference.fna.fai', 'https://example.org/assemblies/GCF_000739105.1/reference/reference.fna.fai', 'example.org', 'text/plain', 28, '755121207de0dc2542b2c2a642208e78152ae32901713869b8f54f0b4ed55987', 1, 'verified_redistributable', 1, 1),
('GCF_000739105.1/reference/genes.gff3.gz', 'v0.2.0', 'GCF_000739105.1', NULL, 'gff3', 'assemblies/GCF_000739105.1/reference/genes.gff3.gz', 'https://example.org/assemblies/GCF_000739105.1/reference/genes.gff3.gz', 'example.org', 'application/gzip', 142587, 'dcc5b339e6b8f31289c9db6cbb0eda99a51faf4d7be8d5076ff7a86b8f247893', 1, 'verified_redistributable', 1, 1),
('GCF_000739105.1/reference/genes.gff3.gz.tbi', 'v0.2.0', 'GCF_000739105.1', NULL, 'tbi', 'assemblies/GCF_000739105.1/reference/genes.gff3.gz.tbi', 'https://example.org/assemblies/GCF_000739105.1/reference/genes.gff3.gz.tbi', 'example.org', 'application/octet-stream', 1589, '042eb4a3095719cb60ec73fa8feb6ce808b908f7b1661af75dcbc6265b7f01b2', 1, 'verified_redistributable', 1, 1),
('GCF_000739105.1/tracks/BATTER_S1_007.endpoints.bed', 'v0.2.0', 'GCF_000739105.1', 'BATTER_S1_007', 'bed', 'records/BATTER_S1_007/endpoints.bed', 'https://example.org/records/BATTER_S1_007/endpoints.bed', 'example.org', 'text/plain', 74306, '8926da72886e01d8fd7c87ecb3b8a5851abca6fdf161be25b11c4f36a130f083', 1, 'verified_redistributable', 1, 1),
('GCF_000739105.1/tracks/BATTER_S1_013.endpoints.bed', 'v0.2.0', 'GCF_000739105.1', 'BATTER_S1_013', 'bed', 'records/BATTER_S1_013/endpoints.bed', 'https://example.org/records/BATTER_S1_013/endpoints.bed', 'example.org', 'text/plain', 41063, 'a2037893175f9498f1e11c47a903bf5f9845ec178486349e600abb2e4995247d', 1, 'verified_redistributable', 1, 1);

INSERT INTO tracks (
  track_id, release_version, source_id, assembly_accession, publication_year, pmid,
  doi, paper_title, journal, raw_accessions_json, assay, evidence_class, record_count,
  asset_key, is_public, display_order, metadata_json
) VALUES
('BATTER_S1_007_termseq_teps', 'v0.2.0', 'BATTER_S1_007', 'GCF_000739105.1', 2019, '31555254', NULL, 'The Transcription Unit Architecture of Streptomyces lividans TK24', 'Example Journal', '["PRJEB31507"]', 'Term-seq / dRNA-seq', 'author_called_endpoint', 1640, 'GCF_000739105.1/tracks/BATTER_S1_007.endpoints.bed', 1, 1, '{}'),
('BATTER_S1_013_termseq_tts', 'v0.2.0', 'BATTER_S1_013', 'GCF_000739105.1', 2020, '33319794', NULL, 'Genome-scale determination of 5′ and 3′ boundaries in Streptomyces genomes', 'Example Journal', '["PRJEB31507"]', 'Term-seq / dRNA-seq', 'author_called_endpoint', 1208, 'GCF_000739105.1/tracks/BATTER_S1_013.endpoints.bed', 1, 2, '{}');
