-- BTED v0.3 PostgreSQL schema skeleton
--
-- This DDL is a derived-query-layer contract.  It intentionally contains no
-- seed data and no DROP/TRUNCATE statements.  A future importer must load a
-- new release in staging, validate it, and switch the published release in a
-- transaction.  The canonical release under data/public remains the source
-- of truth.

BEGIN;

CREATE TABLE release_versions (
    release_version TEXT PRIMARY KEY,
    release_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    release_date DATE,
    canonical_manifest_path TEXT NOT NULL,
    canonical_manifest_sha256 TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'staged',
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT release_versions_release_id_uq UNIQUE (release_id),
    CONSTRAINT release_versions_version_ck
        CHECK (release_version ~ '^v[0-9]+[.][0-9]+[.][0-9]+$'),
    CONSTRAINT release_versions_sha256_ck
        CHECK (canonical_manifest_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT release_versions_current_status_ck
        CHECK (NOT is_current OR status = 'published'),
    CONSTRAINT release_versions_status_ck
        CHECK (status IN ('staged', 'validated', 'published', 'retired'))
);

CREATE UNIQUE INDEX release_versions_one_current_idx
    ON release_versions (is_current)
    WHERE is_current;

CREATE TABLE import_runs (
    import_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_version TEXT NOT NULL
        REFERENCES release_versions (release_version) ON DELETE RESTRICT,
    importer_name TEXT NOT NULL,
    importer_version TEXT NOT NULL,
    input_manifest_path TEXT NOT NULL,
    input_manifest_sha256 TEXT NOT NULL,
    staging_location TEXT,
    run_status TEXT NOT NULL DEFAULT 'staging',
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    validation_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_summary TEXT,
    committed_at TIMESTAMPTZ,
    CONSTRAINT import_runs_manifest_sha256_ck
        CHECK (input_manifest_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT import_runs_status_ck
        CHECK (run_status IN ('staging', 'validating', 'validated', 'committed', 'failed', 'aborted')),
    CONSTRAINT import_runs_time_ck
        CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX import_runs_release_status_idx
    ON import_runs (release_version, run_status);
CREATE INDEX import_runs_input_manifest_idx
    ON import_runs (release_version, input_manifest_sha256, started_at);

CREATE TABLE publications (
    publication_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pmid TEXT NOT NULL,
    doi TEXT,
    pmc TEXT,
    published_year SMALLINT,
    journal TEXT,
    paper_title TEXT NOT NULL,
    citation_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT publications_pmid_ck CHECK (pmid ~ '^[0-9]+$'),
    CONSTRAINT publications_year_ck
        CHECK (published_year IS NULL OR published_year BETWEEN 1800 AND 2200)
);

CREATE UNIQUE INDEX publications_pmid_uq ON publications (pmid);
CREATE UNIQUE INDEX publications_doi_lower_uq
    ON publications (lower(doi))
    WHERE doi IS NOT NULL;

CREATE TABLE assemblies (
    assembly_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_accession TEXT NOT NULL,
    assembly_name TEXT,
    organism_name TEXT,
    strain TEXT,
    taxon_id INTEGER,
    reference_url TEXT,
    CONSTRAINT assemblies_accession_uq UNIQUE (assembly_accession),
    CONSTRAINT assemblies_accession_ck
        CHECK (assembly_accession ~ '^(GCA|GCF)_[0-9]+[.][0-9]+$')
);

CREATE TABLE contigs (
    contig_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_id BIGINT NOT NULL
        REFERENCES assemblies (assembly_id) ON DELETE RESTRICT,
    contig_accession TEXT NOT NULL,
    contig_name TEXT NOT NULL,
    length_bp BIGINT NOT NULL,
    sequence_sha256 TEXT,
    CONSTRAINT contigs_length_ck CHECK (length_bp > 0),
    CONSTRAINT contigs_sha256_ck
        CHECK (sequence_sha256 IS NULL OR sequence_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT contigs_accession_uq UNIQUE (assembly_id, contig_accession),
    CONSTRAINT contigs_name_uq UNIQUE (assembly_id, contig_name),
    CONSTRAINT contigs_id_assembly_uq UNIQUE (contig_id, assembly_id)
);

CREATE INDEX contigs_assembly_idx ON contigs (assembly_id);

CREATE TABLE sources (
    source_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_version TEXT NOT NULL
        REFERENCES release_versions (release_version) ON DELETE RESTRICT,
    source_id TEXT NOT NULL,
    publication_id BIGINT NOT NULL
        REFERENCES publications (publication_id) ON DELETE RESTRICT,
    assembly_id BIGINT NOT NULL
        REFERENCES assemblies (assembly_id) ON DELETE RESTRICT,
    species TEXT NOT NULL,
    phylum TEXT,
    assay_family TEXT NOT NULL,
    release_status TEXT NOT NULL,
    evidence_class TEXT NOT NULL,
    redistribution_status TEXT NOT NULL,
    accessibility_status TEXT NOT NULL,
    coordinate_status TEXT NOT NULL,
    processing_status TEXT NOT NULL,
    -- Preserve the Table S1 spelling; API may expose a derived alias.
    used_for_batter_augmentation BOOLEAN NOT NULL,
    record_count INTEGER NOT NULL DEFAULT 0,
    has_jbrowse BOOLEAN NOT NULL DEFAULT FALSE,
    manifest_path TEXT NOT NULL,
    manifest_sha256 TEXT NOT NULL,
    record_root TEXT,
    source_note TEXT,
    decision_note TEXT,
    known_limitations TEXT,
    CONSTRAINT sources_release_source_uq UNIQUE (release_version, source_id),
    CONSTRAINT sources_release_pk_uq UNIQUE (release_version, source_pk),
    CONSTRAINT sources_record_count_ck CHECK (record_count >= 0),
    CONSTRAINT sources_manifest_sha256_ck
        CHECK (manifest_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT sources_status_ck
        CHECK (release_status IN ('published_standardized', 'audit_only', 'to_review', 'blocked')),
    CONSTRAINT sources_evidence_ck
        CHECK (evidence_class IN (
            'observed_signal',
            'called_endpoint',
            'author_called_endpoint',
            'curated_record',
            'author_integrated_mixed_evidence',
            'prediction_only',
            'NA'
        )),
    CONSTRAINT sources_public_state_ck
        CHECK (
            (
                release_status = 'published_standardized'
                AND record_count > 0
                AND evidence_class IN (
                    'observed_signal',
                    'called_endpoint',
                    'author_called_endpoint',
                    'curated_record'
                )
            )
            OR (
                release_status = 'audit_only'
                AND record_count = 0
                AND has_jbrowse = FALSE
                AND evidence_class = 'NA'
            )
            OR (
                release_status IN ('to_review', 'blocked')
                AND record_count = 0
                AND has_jbrowse = FALSE
            )
        )
);

CREATE INDEX sources_release_status_idx
    ON sources (release_version, release_status);
CREATE INDEX sources_assembly_idx ON sources (assembly_id);
CREATE INDEX sources_augmentation_idx
    ON sources (release_version, used_for_batter_augmentation)
    WHERE used_for_batter_augmentation;

CREATE TABLE source_accessions (
    source_accession_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_pk BIGINT NOT NULL
        REFERENCES sources (source_pk) ON DELETE RESTRICT,
    accession_namespace TEXT NOT NULL,
    accession TEXT NOT NULL,
    raw_value TEXT NOT NULL,
    accession_type TEXT NOT NULL,
    ordinal INTEGER,
    external_url TEXT,
    CONSTRAINT source_accessions_namespace_ck
        CHECK (accession_namespace ~ '^[A-Za-z0-9_]+$'),
    CONSTRAINT source_accessions_normalized_ck
        CHECK (accession = btrim(accession) AND accession !~ '[,;[:space:]]'),
    CONSTRAINT source_accessions_ordinal_ck
        CHECK (ordinal IS NULL OR ordinal > 0),
    CONSTRAINT source_accessions_uq
        UNIQUE (source_pk, accession_namespace, accession)
);

CREATE INDEX source_accessions_lookup_idx
    ON source_accessions (accession_namespace, accession);

CREATE TABLE samples (
    sample_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_pk BIGINT NOT NULL
        REFERENCES sources (source_pk) ON DELETE RESTRICT,
    sample_id TEXT NOT NULL,
    sample_label TEXT,
    biological_condition TEXT,
    replicate_label TEXT,
    sample_accession TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT samples_id_ck CHECK (sample_id = btrim(sample_id) AND sample_id <> ''),
    CONSTRAINT samples_source_id_uq UNIQUE (source_pk, sample_id),
    CONSTRAINT samples_source_id_pk_uq UNIQUE (source_pk, sample_id, sample_pk)
);

CREATE TABLE endpoints (
    endpoint_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_version TEXT NOT NULL
        REFERENCES release_versions (release_version) ON DELETE RESTRICT,
    source_pk BIGINT NOT NULL,
    contig_id BIGINT NOT NULL
        REFERENCES contigs (contig_id) ON DELETE RESTRICT,
    sample_pk BIGINT NOT NULL
        REFERENCES samples (sample_pk) ON DELETE RESTRICT,

    -- The following 24 columns are the lossless v0.2 endpoints.tsv contract.
    end_id TEXT NOT NULL,
    source_id TEXT NOT NULL,
    sample_id TEXT NOT NULL,
    assay TEXT NOT NULL,
    evidence_class TEXT NOT NULL,
    author_endpoint_id TEXT NOT NULL,
    published_reference_accession TEXT NOT NULL,
    reference_assembly TEXT NOT NULL,
    reference_name TEXT NOT NULL,
    replicon_label TEXT NOT NULL,
    biological_coordinate_1based BIGINT NOT NULL,
    bed_start_0based BIGINT NOT NULL,
    bed_end_0based BIGINT NOT NULL,
    strand CHAR(1) NOT NULL,
    signal_or_score TEXT NOT NULL,
    author_category TEXT NOT NULL,
    associated_gene_or_locus TEXT NOT NULL,
    pmid TEXT NOT NULL,
    doi TEXT NOT NULL,
    source_table_or_file TEXT NOT NULL,
    coordinate_interpretation TEXT NOT NULL,
    original_row_reference TEXT NOT NULL,
    qc_status TEXT NOT NULL,
    note TEXT NOT NULL,

    CONSTRAINT endpoints_release_source_fk
        FOREIGN KEY (release_version, source_pk)
        REFERENCES sources (release_version, source_pk) ON DELETE RESTRICT,
    CONSTRAINT endpoints_sample_context_fk
        FOREIGN KEY (source_pk, sample_id, sample_pk)
        REFERENCES samples (source_pk, sample_id, sample_pk) ON DELETE RESTRICT,
    CONSTRAINT endpoints_release_pk_uq UNIQUE (release_version, endpoint_pk),
    CONSTRAINT endpoints_release_end_uq UNIQUE (release_version, end_id),
    CONSTRAINT endpoints_release_source_end_uq
        UNIQUE (release_version, source_pk, end_id),
    CONSTRAINT endpoints_evidence_ck
        CHECK (evidence_class IN (
            'observed_signal',
            'called_endpoint',
            'author_called_endpoint',
            'curated_record'
        )),
    CONSTRAINT endpoints_coordinate_ck
        CHECK (
            biological_coordinate_1based >= 1
            AND bed_start_0based >= 0
            AND bed_end_0based > bed_start_0based
            AND bed_start_0based = biological_coordinate_1based - 1
            AND bed_end_0based = biological_coordinate_1based
        ),
    CONSTRAINT endpoints_strand_ck CHECK (strand IN ('+', '-')),
    CONSTRAINT endpoints_pmid_ck CHECK (pmid ~ '^[0-9]+$')
);

CREATE INDEX endpoints_release_source_idx
    ON endpoints (release_version, source_pk, end_id);
CREATE INDEX endpoints_contig_position_idx
    ON endpoints (contig_id, biological_coordinate_1based, strand);
CREATE INDEX endpoints_release_evidence_idx
    ON endpoints (release_version, evidence_class);
CREATE INDEX endpoints_sample_idx ON endpoints (source_pk, sample_id);

CREATE TABLE source_annotations (
    annotation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_version TEXT NOT NULL
        REFERENCES release_versions (release_version) ON DELETE RESTRICT,
    source_pk BIGINT NOT NULL,
    end_id TEXT NOT NULL,
    annotation_kind TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    ordinal INTEGER NOT NULL DEFAULT 1,
    annotation_json JSONB NOT NULL,
    provenance_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT source_annotations_release_source_fk
        FOREIGN KEY (release_version, source_pk)
        REFERENCES sources (release_version, source_pk) ON DELETE RESTRICT,
    CONSTRAINT source_annotations_release_source_end_fk
        FOREIGN KEY (release_version, source_pk, end_id)
        REFERENCES endpoints (release_version, source_pk, end_id) ON DELETE RESTRICT,
    CONSTRAINT source_annotations_kind_ck
        CHECK (annotation_kind IN (
            'experimental_measurement',
            'author_annotation',
            'prediction_annotation',
            'curation_metadata'
        )),
    CONSTRAINT source_annotations_object_ck
        CHECK (jsonb_typeof(annotation_json) = 'object'),
    CONSTRAINT source_annotations_provenance_object_ck
        CHECK (jsonb_typeof(provenance_json) = 'object'),
    CONSTRAINT source_annotations_ordinal_ck CHECK (ordinal > 0),
    CONSTRAINT source_annotations_uq
        UNIQUE (release_version, end_id, annotation_kind, source_record_id, ordinal)
);

CREATE INDEX source_annotations_json_idx
    ON source_annotations USING GIN (annotation_json);

CREATE TABLE genes (
    gene_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_version TEXT NOT NULL
        REFERENCES release_versions (release_version) ON DELETE RESTRICT,
    assembly_id BIGINT NOT NULL
        REFERENCES assemblies (assembly_id) ON DELETE RESTRICT,
    contig_id BIGINT NOT NULL
        REFERENCES contigs (contig_id) ON DELETE RESTRICT,
    gene_id TEXT NOT NULL,
    locus_tag TEXT,
    gene_name TEXT,
    feature_type TEXT NOT NULL,
    start_1based BIGINT NOT NULL,
    end_1based BIGINT NOT NULL,
    strand CHAR(1) NOT NULL,
    annotation_asset_id TEXT NOT NULL,
    annotation_sha256 TEXT NOT NULL,
    attributes_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT genes_coordinate_ck
        CHECK (start_1based >= 1 AND end_1based >= start_1based),
    CONSTRAINT genes_strand_ck CHECK (strand IN ('+', '-')),
    CONSTRAINT genes_sha256_ck CHECK (annotation_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT genes_contig_assembly_fk
        FOREIGN KEY (contig_id, assembly_id)
        REFERENCES contigs (contig_id, assembly_id) ON DELETE RESTRICT,
    CONSTRAINT genes_release_pk_uq UNIQUE (release_version, gene_pk),
    CONSTRAINT genes_uq UNIQUE (release_version, assembly_id, contig_id, gene_id)
);

CREATE INDEX genes_contig_position_idx
    ON genes (contig_id, start_1based, end_1based);

CREATE TABLE endpoint_gene_context (
    release_version TEXT NOT NULL
        REFERENCES release_versions (release_version) ON DELETE RESTRICT,
    endpoint_pk BIGINT NOT NULL,
    gene_pk BIGINT NOT NULL
        REFERENCES genes (gene_pk) ON DELETE RESTRICT,
    relation_type TEXT NOT NULL,
    distance_nt INTEGER NOT NULL,
    method TEXT NOT NULL,
    algorithm_version TEXT NOT NULL,
    context_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT endpoint_gene_context_endpoint_fk
        FOREIGN KEY (release_version, endpoint_pk)
        REFERENCES endpoints (release_version, endpoint_pk) ON DELETE RESTRICT,
    CONSTRAINT endpoint_gene_context_gene_release_fk
        FOREIGN KEY (release_version, gene_pk)
        REFERENCES genes (release_version, gene_pk) ON DELETE RESTRICT,
    CONSTRAINT endpoint_gene_context_relation_ck
        CHECK (relation_type IN ('upstream', 'downstream', 'overlap', 'nearest')),
    CONSTRAINT endpoint_gene_context_distance_ck CHECK (distance_nt >= 0),
    CONSTRAINT endpoint_gene_context_uq
        PRIMARY KEY (release_version, endpoint_pk, gene_pk, relation_type)
);

CREATE INDEX endpoint_gene_context_gene_idx
    ON endpoint_gene_context (gene_pk, relation_type);

CREATE TABLE assets (
    asset_id TEXT PRIMARY KEY,
    release_version TEXT NOT NULL
        REFERENCES release_versions (release_version) ON DELETE RESTRICT,
    source_pk BIGINT,
    assembly_id BIGINT
        REFERENCES assemblies (assembly_id) ON DELETE RESTRICT,
    asset_kind TEXT NOT NULL,
    logical_path TEXT NOT NULL,
    origin_url TEXT NOT NULL,
    origin_host TEXT NOT NULL,
    byte_size BIGINT NOT NULL,
    sha256 TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    supports_range BOOLEAN NOT NULL DEFAULT FALSE,
    redistribution_status TEXT NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT assets_release_source_fk
        FOREIGN KEY (release_version, source_pk)
        REFERENCES sources (release_version, source_pk) ON DELETE RESTRICT,
    CONSTRAINT assets_kind_ck
        CHECK (asset_kind IN (
            'fasta', 'fai', 'gff3', 'tbi', 'bigwig', 'bed', 'config',
            'metadata', 'checksum', 'archive', 'release_manifest', 'other'
        )),
    CONSTRAINT assets_size_ck CHECK (byte_size >= 0),
    CONSTRAINT assets_sha256_ck CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT assets_redistribution_ck
        CHECK (redistribution_status IN (
            'verified_redistributable', 'external_link_only', 'audit_only', 'to_review'
        )),
    CONSTRAINT assets_scope_ck CHECK (
        source_pk IS NOT NULL
        OR assembly_id IS NOT NULL
        OR asset_kind IN ('release_manifest', 'archive', 'checksum')
    ),
    CONSTRAINT assets_release_asset_uq UNIQUE (release_version, asset_id),
    CONSTRAINT assets_release_path_uq UNIQUE (release_version, logical_path)
);

CREATE INDEX assets_release_kind_idx ON assets (release_version, asset_kind);
CREATE INDEX assets_source_idx ON assets (source_pk) WHERE source_pk IS NOT NULL;
CREATE INDEX assets_assembly_idx ON assets (assembly_id) WHERE assembly_id IS NOT NULL;

ALTER TABLE genes
    ADD CONSTRAINT genes_annotation_asset_fk
    FOREIGN KEY (release_version, annotation_asset_id)
    REFERENCES assets (release_version, asset_id) ON DELETE RESTRICT;

CREATE FUNCTION bted_guard_gene_annotation() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_contig_length BIGINT;
    v_asset_sha256 TEXT;
    v_asset_kind TEXT;
BEGIN
    SELECT c.length_bp
      INTO v_contig_length
      FROM contigs AS c
     WHERE c.contig_id = NEW.contig_id
       AND c.assembly_id = NEW.assembly_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'gene contig does not belong to gene assembly';
    END IF;
    IF NEW.end_1based > v_contig_length THEN
        RAISE EXCEPTION 'gene end % exceeds contig length %',
            NEW.end_1based, v_contig_length;
    END IF;

    SELECT a.sha256, a.asset_kind
      INTO v_asset_sha256, v_asset_kind
      FROM assets AS a
     WHERE a.release_version = NEW.release_version
       AND a.asset_id = NEW.annotation_asset_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'gene annotation asset is not registered in this release';
    END IF;
    IF v_asset_kind <> 'gff3' THEN
        RAISE EXCEPTION 'gene annotation asset must be a registered GFF3 asset';
    END IF;
    IF v_asset_sha256 <> NEW.annotation_sha256 THEN
        RAISE EXCEPTION 'gene annotation checksum does not match registered asset';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER genes_annotation_guard
    BEFORE INSERT OR UPDATE ON genes
    FOR EACH ROW EXECUTE FUNCTION bted_guard_gene_annotation();

-- Public endpoints may never be prediction-only, mixed-evidence, audit-only,
-- to_review, or blocked rows.  The source/release/contig checks live here
-- because a plain CHECK cannot inspect a referenced row.
CREATE FUNCTION bted_guard_public_endpoint() RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_source_id TEXT;
    v_release_status TEXT;
    v_source_evidence TEXT;
    v_source_assembly BIGINT;
    v_contig_assembly BIGINT;
    v_contig_length BIGINT;
    v_expected_assembly TEXT;
BEGIN
    IF NEW.evidence_class IN ('author_integrated_mixed_evidence', 'prediction_only') THEN
        RAISE EXCEPTION 'forbidden public endpoint evidence class: %', NEW.evidence_class;
    END IF;

    SELECT s.source_id, s.release_status, s.evidence_class, s.assembly_id
      INTO v_source_id, v_release_status, v_source_evidence, v_source_assembly
      FROM sources AS s
     WHERE s.release_version = NEW.release_version
       AND s.source_pk = NEW.source_pk;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'endpoint source/release does not exist: % / %',
            NEW.release_version, NEW.source_pk;
    END IF;
    IF v_source_id <> NEW.source_id THEN
        RAISE EXCEPTION 'endpoint source_id does not match sources.source_id';
    END IF;
    IF v_release_status <> 'published_standardized' THEN
        RAISE EXCEPTION 'endpoint cannot be attached to source status %', v_release_status;
    END IF;
    IF v_source_evidence IN ('author_integrated_mixed_evidence', 'prediction_only', 'NA') THEN
        RAISE EXCEPTION 'source evidence is not public endpoint evidence: %', v_source_evidence;
    END IF;

    SELECT c.assembly_id, c.length_bp
      INTO v_contig_assembly, v_contig_length
      FROM contigs AS c
     WHERE c.contig_id = NEW.contig_id;
    IF v_source_assembly IS DISTINCT FROM v_contig_assembly THEN
        RAISE EXCEPTION 'endpoint contig belongs to a different assembly';
    END IF;
    IF NEW.biological_coordinate_1based > v_contig_length THEN
        RAISE EXCEPTION 'endpoint position % exceeds contig length %',
            NEW.biological_coordinate_1based, v_contig_length;
    END IF;

    SELECT a.assembly_accession
      INTO v_expected_assembly
      FROM assemblies AS a
     WHERE a.assembly_id = v_source_assembly;
    IF v_expected_assembly <> NEW.reference_assembly THEN
        RAISE EXCEPTION 'endpoint reference_assembly does not match source assembly';
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM samples AS sm
         WHERE sm.sample_pk = NEW.sample_pk
           AND sm.source_pk = NEW.source_pk
           AND sm.sample_id = NEW.sample_id
    ) THEN
        RAISE EXCEPTION 'endpoint sample_pk/sample_id/source_pk do not match';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER endpoints_public_guard
    BEFORE INSERT OR UPDATE ON endpoints
    FOR EACH ROW EXECUTE FUNCTION bted_guard_public_endpoint();

CREATE FUNCTION bted_guard_source_state() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.release_status = 'audit_only'
       AND EXISTS (
           SELECT 1 FROM endpoints AS e
            WHERE e.release_version = OLD.release_version
              AND e.source_pk = OLD.source_pk
       ) THEN
        RAISE EXCEPTION 'audit_only source cannot retain endpoint rows';
    END IF;
    IF NEW.release_status <> 'published_standardized'
       AND NEW.has_jbrowse THEN
        RAISE EXCEPTION 'non-published source cannot expose JBrowse';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER sources_state_guard
    BEFORE UPDATE ON sources
    FOR EACH ROW EXECUTE FUNCTION bted_guard_source_state();

COMMENT ON TABLE release_versions IS
    'Versioned canonical release registry; PostgreSQL is a derived query layer.';
COMMENT ON TABLE endpoints IS
    'Public endpoint rows with all 24 v0.2 endpoints.tsv columns preserved.';
COMMENT ON TABLE source_annotations IS
    'Lossless source-specific fields in JSONB; prediction_annotation never changes endpoint evidence.';
COMMENT ON TABLE assets IS
    'Registered, checksum-pinned assets served through the same-origin Range proxy.';

COMMIT;
