"""Build a deterministic, database-shaped BTED staging bundle.

The bundle is an auditable intermediate representation, not a PostgreSQL
dump.  It is built only after :mod:`backend.importer.canonical` has validated
the canonical release and the reference-contig registry.  No database driver,
network request, or biological interpretation is involved here.

Every table is written as UTF-8 JSONL with stable key ordering.  Identity
columns generated by PostgreSQL are represented by explicit ``*_ref`` natural
keys so that a future writer can resolve foreign keys in a transaction.
"""

from __future__ import annotations

import csv
import hashlib
import json
import os
import re
import shutil
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping
from urllib.parse import quote, urlparse

from .canonical import (
    V02_ENDPOINT_COLUMNS,
    CanonicalReleaseValidator,
    sha256_file,
)


MATERIALIZER_VERSION = "bted-materializer-0.3.0-b1"
MATERIALIZATION_SCHEMA_VERSION = "bted-postgresql-staging-0.3.0"
ANNOTATION_KINDS = (
    "experimental_measurement",
    "author_annotation",
    "prediction_annotation",
    "curation_metadata",
)
ROLE_TO_ANNOTATION_KIND = {
    "experimental_measurement": "experimental_measurement",
    "author_annotation": "author_annotation",
    "author_called_endpoint": "author_annotation",
    "prediction_annotation": "prediction_annotation",
    "curation_metadata": "curation_metadata",
}
TABLE_ORDER = (
    "release_versions",
    "import_runs",
    "publications",
    "assemblies",
    "contigs",
    "sources",
    "source_accessions",
    "samples",
    "endpoints",
    "source_annotations",
    "genes",
    "endpoint_gene_context",
    "assets",
)
INTEGER_ENDPOINT_COLUMNS = {
    "biological_coordinate_1based",
    "bed_start_0based",
    "bed_end_0based",
}
SOURCE_STATUS_PUBLISHED = {"published_standardized", "published"}


class MaterializationError(RuntimeError):
    """Raised when a validated release cannot be safely materialized."""


@dataclass(frozen=True)
class MaterializationResult:
    """Result of a successful staging-bundle build."""

    output_dir: Path
    manifest: dict[str, Any]

    @property
    def table_counts(self) -> dict[str, int]:
        return {
            name: int(value.get("row_count", 0))
            for name, value in self.manifest.get("tables", {}).items()
        }


def _utc_timestamp(value: str | None) -> str:
    if value is None:
        parsed = datetime.now(timezone.utc)
    else:
        raw = str(value).strip()
        try:
            parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        except ValueError as exc:
            raise MaterializationError(
                "generated_at_utc must be ISO-8601 with an explicit timezone"
            ) from exc
        if parsed.tzinfo is None:
            raise MaterializationError(
                "generated_at_utc must include a timezone (for example, Z)"
            )
    parsed = parsed.astimezone(timezone.utc).replace(microsecond=0)
    return parsed.isoformat().replace("+00:00", "Z")


def _validate_origin_base(value: str) -> tuple[str, str]:
    raw = str(value or "").strip()
    parsed = urlparse(raw)
    if parsed.scheme != "https" or not parsed.hostname:
        raise MaterializationError("asset_origin_base must be an HTTPS URL with a hostname")
    if parsed.username or parsed.password or parsed.query or parsed.fragment:
        raise MaterializationError(
            "asset_origin_base must not contain credentials, query parameters, or fragments"
        )
    base = raw.rstrip("/")
    return base, parsed.hostname


def _int(value: Any, field: str) -> int:
    try:
        return int(str(value))
    except (TypeError, ValueError) as exc:
        raise MaterializationError(f"{field} must be an integer: {value!r}") from exc


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _write_jsonl(path: Path, rows: Iterable[Mapping[str, Any]]) -> tuple[int, str, int]:
    count = 0
    digest = hashlib.sha256()
    size = 0
    with path.open("wb") as handle:
        for row in rows:
            payload = (
                json.dumps(
                    dict(row),
                    ensure_ascii=False,
                    sort_keys=True,
                    separators=(",", ":"),
                ).encode("utf-8")
                + b"\n"
            )
            handle.write(payload)
            digest.update(payload)
            size += len(payload)
            count += 1
    return count, digest.hexdigest(), size


def _json_file(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise MaterializationError(f"cannot read JSON metadata: {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise MaterializationError(f"JSON metadata must be an object: {path}")
    return value


def _release_entry(snapshot: Mapping[str, Any], source_id: str) -> Mapping[str, Any]:
    entry = snapshot["release"].get("sources", {}).get(source_id)
    if not isinstance(entry, Mapping):
        raise MaterializationError(f"release entry missing for {source_id}")
    return entry


def _source_manifest(snapshot: Mapping[str, Any], source_id: str) -> Mapping[str, Any]:
    manifest = snapshot.get("source_manifests", {}).get(source_id)
    if not isinstance(manifest, Mapping):
        raise MaterializationError(f"canonical source manifest missing for {source_id}")
    return manifest


def _registry_row(snapshot: Mapping[str, Any], source_id: str) -> Mapping[str, Any]:
    row = snapshot.get("registry_rows", {}).get(source_id)
    if not isinstance(row, Mapping):
        raise MaterializationError(f"source registry row missing for {source_id}")
    return row


def _source_manifest_path(snapshot: Mapping[str, Any], source_id: str) -> str:
    path = snapshot.get("declared_files", {}).get(source_id, {}).get("manifest.json")
    if path is None:
        raise MaterializationError(f"canonical manifest path missing for {source_id}")
    release_root = Path(str(snapshot["release_root"])).resolve()
    try:
        return Path(str(path)).resolve().relative_to(release_root).as_posix()
    except ValueError:
        return Path(str(path)).name


def _source_manifest_sha(snapshot: Mapping[str, Any], source_id: str) -> str:
    value = snapshot.get("declared_file_sha256", {}).get(source_id, {}).get("manifest.json", "")
    if not re.fullmatch(r"[0-9a-f]{64}", str(value)):
        raise MaterializationError(f"canonical manifest checksum missing for {source_id}")
    return str(value)


def _parse_flag(value: Any, source_id: str) -> bool:
    if str(value).upper() == "TRUE":
        return True
    if str(value).upper() == "FALSE":
        return False
    raise MaterializationError(f"used_for_batter_augmentation must be TRUE/FALSE for {source_id}")


def _raw_accessions(value: Any) -> list[str]:
    return sorted({part.strip() for part in str(value or "").split(";") if part.strip()})


def _accession_namespace(accession: str) -> tuple[str, str | None]:
    upper = accession.upper()
    if upper.startswith("GSE"):
        return "GEO", None
    if upper.startswith("SR") or upper.startswith("PRJNA"):
        return "SRA", None
    if upper.startswith("PRJEB"):
        return "ENA", None
    if upper.startswith("E-MTAB"):
        return "BioStudies", "ArrayExpress"
    raise MaterializationError(f"unknown accession namespace: {accession}")


def _accession_url(namespace: str, accession: str) -> str:
    if namespace == "GEO":
        return f"https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc={quote(accession)}"
    if namespace == "SRA":
        return f"https://www.ncbi.nlm.nih.gov/sra/{quote(accession)}"
    if namespace == "ENA":
        return f"https://www.ebi.ac.uk/ena/browser/view/{quote(accession)}"
    return f"https://www.ebi.ac.uk/biostudies/arrayexpress/studies/{quote(accession)}"


def _mime_type(logical_path: str, asset_kind: str) -> str:
    suffix = Path(logical_path).suffix.lower()
    if suffix == ".json":
        return "application/json"
    if suffix in {".tsv", ".tab"}:
        return "text/tab-separated-values"
    if suffix in {".bed", ".gff", ".gff3", ".txt", ".fai"}:
        return "text/plain"
    if suffix in {".gz", ".bgz"}:
        return "application/gzip"
    if asset_kind == "bigwig":
        return "application/octet-stream"
    return "application/octet-stream"


def _asset_origin(base: str, asset_id: str) -> str:
    # asset_id is already a single path segment by canonical validation.
    return f"{base}/{quote(asset_id, safe="-._~")}"  # noqa: E501


def _load_field_roles(path: Path) -> tuple[dict[str, str], dict[str, dict[str, Any]]]:
    metadata = _json_file(path)
    source = metadata.get("source_annotations", {})
    if not isinstance(source, Mapping):
        return {}, {}
    descriptors = source.get("fields", [])
    if not isinstance(descriptors, list):
        raise MaterializationError(f"source_annotations.fields must be an array: {path}")
    roles: dict[str, str] = {}
    provenance: dict[str, dict[str, Any]] = {}
    for descriptor in descriptors:
        if not isinstance(descriptor, Mapping):
            raise MaterializationError(f"invalid field descriptor in {path}")
        original_name = str(descriptor.get("original_name", "")).strip()
        role = str(descriptor.get("evidence_role", "")).strip()
        if not original_name:
            continue
        if role not in ROLE_TO_ANNOTATION_KIND:
            raise MaterializationError(
                f"unsupported evidence_role {role!r} for column {original_name!r} in {path}"
            )
        if original_name in roles and roles[original_name] != role:
            raise MaterializationError(f"conflicting evidence_role for {original_name} in {path}")
        roles[original_name] = role
        provenance[original_name] = {
            "field_name": descriptor.get("name"),
            "original_name": original_name,
            "evidence_role": role,
            "data_type": descriptor.get("data_type"),
            "units": descriptor.get("units"),
            "description": descriptor.get("description"),
        }
    return roles, provenance


def _build_annotations(
    snapshot: Mapping[str, Any],
    source_ids: list[str],
) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for source_id in source_ids:
        rows = snapshot.get("source_annotation_rows", {}).get(source_id, [])
        if not rows:
            continue
        fields_path = snapshot.get("declared_files", {}).get(source_id, {}).get("fields.json")
        if not fields_path:
            raise MaterializationError(f"fields.json path missing for annotated source {source_id}")
        roles, _role_metadata = _load_field_roles(Path(str(fields_path)))
        counters: Counter[tuple[str, str, str]] = Counter()
        for line_number, raw_row in enumerate(rows, start=2):
            row = {str(k): "" if v is None else str(v) for k, v in raw_row.items()}
            end_id = row.get("end_id", "").strip()
            if not end_id:
                raise MaterializationError(
                    f"source annotation row has no end_id: {source_id}: line {line_number}"
                )
            source_record_id = (
                row.get("source_record_id", "").strip()
                or row.get("source_end_id", "").strip()
                or row.get("site_id", "").strip()
                or row.get("end_id", "").strip()
                or f"row_{line_number}"
            )
            groups: dict[str, dict[str, str]] = defaultdict(dict)
            unmapped: list[str] = []
            for field_name, value in row.items():
                role = roles.get(field_name)
                if role is None:
                    # Helper columns (for example source_record_id) are
                    # explicit traceability metadata.  They are retained in
                    # the curation group rather than silently dropped or
                    # promoted to experimental evidence.
                    role = "curation_metadata"
                    unmapped.append(field_name)
                kind = ROLE_TO_ANNOTATION_KIND[role]
                groups[kind][field_name] = value
            for kind in sorted(groups):
                counters[(end_id, kind, source_record_id)] += 1
                ordinal = counters[(end_id, kind, source_record_id)]
                group_fields = set(groups[kind])
                provenance = {
                    "source_id": source_id,
                    "source_annotation_file": f"records/{source_id}/source_annotations.tsv",
                    "source_annotation_line": line_number,
                    "source_record_id": source_record_id,
                    "unmapped_header_columns": sorted(group_fields.intersection(unmapped)),
                    "endpoint_evidence_class": row.get("evidence_class", ""),
                }
                # The standard annotation_kind already records the resolved
                # evidence role.  Keep only the exceptional container mapping
                # needed to explain why an author-called field is stored under
                # the schema's author_annotation kind; the complete dictionary
                # is recorded once per source in the bundle manifest below.
                original_author_fields = sorted(
                    field
                    for field in group_fields
                    if roles.get(field) == "author_called_endpoint"
                )
                if kind == "author_annotation" and original_author_fields:
                    provenance["original_evidence_roles"] = {
                        "author_called_endpoint": original_author_fields
                    }
                    provenance["evidence_boundary"] = (
                        "author_called_endpoint fields are represented as author_annotation; "
                        "they are not an independent endpoint evidence record."
                    )
                elif kind == "prediction_annotation":
                    provenance["evidence_boundary"] = (
                        "Prediction annotations are retained as source metadata and do not "
                        "change endpoint evidence_class."
                    )
                output.append(
                    {
                        "release_version": snapshot["release"].get("release_version"),
                        "source_id_ref": source_id,
                        "end_id": end_id,
                        "annotation_kind": kind,
                        "source_record_id": source_record_id,
                        "ordinal": ordinal,
                        "annotation_json": dict(sorted(groups[kind].items())),
                        "provenance_json": provenance,
                    }
                )
    return sorted(
        output,
        key=lambda row: (
            row["source_id_ref"],
            row["end_id"],
            row["annotation_kind"],
            row["source_record_id"],
            row["ordinal"],
        ),
    )


def _release_relative_path(snapshot: Mapping[str, Any], path_value: Any) -> str | None:
    """Return a portable release-relative path, never a local absolute path."""

    if path_value in (None, ""):
        return None
    release_root = Path(str(snapshot["release_root"])).resolve()
    path = Path(str(path_value))
    try:
        return path.resolve().relative_to(release_root).as_posix()
    except ValueError:
        # Canonical validation normally guarantees release-contained files.
        # Keep a portable basename if a compact fixture uses an external
        # symlink/path; never leak the machine-specific absolute path.
        return path.name


def _build_annotation_field_provenance(
    snapshot: Mapping[str, Any],
    source_ids: list[str],
) -> list[dict[str, Any]]:
    """Summarize each source's annotation dictionary once per bundle.

    Per-row annotation records retain values and row-level location only.  The
    relatively verbose field definitions and their SHA-256 are kept here once
    per source, which preserves auditability without multiplying dictionary
    metadata by every evidence-role group and row.
    """

    declared_files = snapshot.get("declared_files", {})
    declared_sha = snapshot.get("declared_file_sha256", {})
    annotation_rows = snapshot.get("source_annotation_rows", {})
    annotation_fields = snapshot.get("source_annotation_fields", {})
    output: list[dict[str, Any]] = []
    for source_id in sorted(source_ids):
        files = declared_files.get(source_id, {})
        checksums = declared_sha.get(source_id, {})
        fields_path = files.get("fields.json")
        if fields_path is None:
            raise MaterializationError(f"fields.json path missing for annotated source {source_id}")
        roles, definitions = _load_field_roles(Path(str(fields_path)))
        header_fields = {
            str(field) for field in annotation_fields.get(source_id, []) if str(field)
        }
        unmapped = sorted(header_fields - set(roles))
        field_definitions = dict(definitions)
        for field in unmapped:
            field_definitions[field] = {
                "original_name": field,
                "evidence_role": "curation_metadata",
                "resolution": "unmapped_header_column_assigned_curation_metadata",
            }
        source_annotation_path = files.get("source_annotations.tsv")
        source_annotation_sha = checksums.get("source_annotations.tsv")
        output.append(
            {
                "source_id": source_id,
                "fields_json_path": _release_relative_path(snapshot, fields_path),
                "fields_json_sha256": str(checksums.get("fields.json", "")),
                "field_roles": {
                    field: roles[field] for field in sorted(roles)
                },
                "field_definitions": {
                    field: field_definitions[field]
                    for field in sorted(field_definitions)
                },
                "unmapped_header_columns": unmapped,
                "source_annotations_path": _release_relative_path(
                    snapshot, source_annotation_path
                ),
                "source_annotations_sha256": (
                    str(source_annotation_sha) if source_annotation_sha else None
                ),
                "source_annotations_row_count": len(annotation_rows.get(source_id, [])),
            }
        )
    return output


def _build_tables(
    snapshot: Mapping[str, Any],
    asset_origin_base: str,
    generated_at_utc: str,
) -> dict[str, list[dict[str, Any]]]:
    release = snapshot["release"]
    release_version = str(release.get("release_version"))
    source_ids = sorted(str(item) for item in snapshot.get("source_ids", []))
    if not source_ids:
        raise MaterializationError("validated snapshot contains no canonical source manifests")
    entries = {sid: _release_entry(snapshot, sid) for sid in source_ids}
    manifests = {sid: _source_manifest(snapshot, sid) for sid in source_ids}
    registry = {sid: _registry_row(snapshot, sid) for sid in source_ids}
    report = snapshot.get("report", {})
    plan = report.get("plan", {}) if isinstance(report, Mapping) else {}
    canonical = plan.get("canonical_manifest", {})
    canonical_sha = str(canonical.get("sha256", ""))
    if not re.fullmatch(r"[0-9a-f]{64}", canonical_sha):
        raise MaterializationError("validated report has no canonical manifest SHA-256")

    # Publication metadata is assembled from canonical manifests.  The
    # validator has already rejected conflicting DOI/title/year values for a
    # shared PMID, so choosing the first sorted source is deterministic.
    publications_by_pmid: dict[str, dict[str, Any]] = {}
    publication_sources: dict[str, list[str]] = defaultdict(list)
    for source_id in source_ids:
        manifest = manifests[source_id]
        pmid = str(manifest.get("pmid", "")).strip()
        if not pmid:
            raise MaterializationError(f"canonical manifest PMID missing for {source_id}")
        publication_sources[pmid].append(source_id)
        if pmid in publications_by_pmid:
            continue
        try:
            published_year = int(str(manifest.get("published_year")))
        except (TypeError, ValueError) as exc:
            raise MaterializationError(f"published_year invalid for {source_id}") from exc
        publications_by_pmid[pmid] = {
            "pmid": pmid,
            "doi": str(manifest.get("doi", "")) or None,
            "pmc": str(manifest.get("pmc", "")) or None,
            "published_year": published_year,
            "journal": None,
            "paper_title": str(manifest.get("paper_title", "")),
            "citation_json": {
                "source_ids": sorted(publication_sources[pmid]),
                "pmid": pmid,
                "doi": str(manifest.get("doi", "")),
                "pmc": str(manifest.get("pmc", "")),
                "paper_title": str(manifest.get("paper_title", "")),
            },
        }
    # Fill source IDs after all source rows are known.
    for pmid, row in publications_by_pmid.items():
        row["citation_json"]["source_ids"] = sorted(publication_sources[pmid])
    publications = [publications_by_pmid[key] for key in sorted(publications_by_pmid)]

    # Assemblies are keyed by their versioned accession.  The full species
    # string is retained; no taxonomic or strain parsing is inferred.
    assembly_members: dict[str, list[str]] = defaultdict(list)
    assembly_species: dict[str, set[str]] = defaultdict(set)
    assembly_strains: dict[str, set[str]] = defaultdict(set)
    assembly_explicit: dict[str, dict[str, set[str]]] = defaultdict(
        lambda: defaultdict(set)
    )
    for source_id in source_ids:
        manifest = manifests[source_id]
        assembly = str(manifest.get("reference_genome", "")).strip()
        species = str(manifest.get("species", "")).strip()
        if not assembly or not species:
            raise MaterializationError(f"assembly/species missing for {source_id}")
        assembly_members[assembly].append(source_id)
        assembly_species[assembly].add(species)
        for field_name in ("assembly_name", "organism_name", "reference_url"):
            value = manifest.get(field_name)
            if value is None:
                value = registry[source_id].get(field_name)
            if value not in (None, ""):
                assembly_explicit[assembly][field_name].add(str(value))
        taxon_value = manifest.get("taxon_id")
        if taxon_value is None:
            taxon_value = registry[source_id].get("taxon_id")
        if taxon_value not in (None, ""):
            assembly_explicit[assembly]["taxon_id"].add(str(taxon_value))
        if manifest.get("strain") is not None:
            assembly_strains[assembly].add(str(manifest["strain"]))
        elif registry[source_id].get("strain") is not None:
            assembly_strains[assembly].add(str(registry[source_id]["strain"]))
    for assembly, species_values in assembly_species.items():
        if len(species_values) != 1 or len(assembly_strains[assembly]) > 1:
            raise MaterializationError(f"shared assembly metadata conflict: {assembly}")
        for field_name, values in assembly_explicit[assembly].items():
            if len(values) > 1:
                raise MaterializationError(
                    f"shared assembly metadata conflict for {assembly}.{field_name}"
                )
        explicit_organism = assembly_explicit[assembly].get("organism_name", set())
        if explicit_organism and explicit_organism != species_values:
            raise MaterializationError(
                f"assembly organism_name is not the validated full species string: {assembly}"
            )
    assemblies = []
    for assembly in sorted(assembly_members):
        members = sorted(assembly_members[assembly])
        species = sorted(assembly_species[assembly])[0]
        strains = sorted(assembly_strains[assembly])
        explicit = assembly_explicit[assembly]
        taxon_values = sorted(explicit.get("taxon_id", set()))
        assemblies.append(
            {
                "assembly_accession": assembly,
                "assembly_name": sorted(explicit.get("assembly_name", set()))[0]
                if explicit.get("assembly_name")
                else assembly,
                "organism_name": sorted(explicit.get("organism_name", set()))[0]
                if explicit.get("organism_name")
                else species,
                "strain": strains[0] if strains else None,
                "taxon_id": _int(taxon_values[0], f"taxon_id {assembly}")
                if taxon_values
                else None,
                "reference_url": sorted(explicit.get("reference_url", set()))[0]
                if explicit.get("reference_url")
                else None,
                "source_ids": members,
            }
        )

    contig_registry = snapshot.get("contig_registry", {})
    contigs: list[dict[str, Any]] = []
    endpoint_rows_by_source = snapshot.get("source_rows", {})
    endpoint_keys: set[tuple[str, str]] = set()
    for source_id in source_ids:
        for row in endpoint_rows_by_source.get(source_id, []):
            endpoint_keys.add((str(row.get("reference_assembly", "")), str(row.get("reference_name", ""))))
    for assembly, contig in sorted(endpoint_keys):
        provenance = contig_registry.get(f"{assembly}\t{contig}")
        if not isinstance(provenance, Mapping):
            raise MaterializationError(f"contig provenance missing: {assembly}/{contig}")
        length_bp = _int(provenance.get("length_bp"), f"length_bp {assembly}/{contig}")
        contigs.append(
            {
                "assembly_id_ref": assembly,
                "assembly_accession": assembly,
                "contig_accession": contig,
                "contig_name": contig,
                "length_bp": length_bp,
                "sequence_sha256": None,
                "provenance_json": dict(sorted(provenance.items())),
            }
        )

    source_rows: list[dict[str, Any]] = []
    source_accessions: list[dict[str, Any]] = []
    sample_keys: set[tuple[str, str]] = set()
    for source_id in source_ids:
        entry = entries[source_id]
        manifest = manifests[source_id]
        registry_row = registry[source_id]
        status = str(entry.get("release_status", ""))
        evidence = str(entry.get("evidence_class", ""))
        try:
            record_count = int(str(entry.get("record_count", 0)))
        except (TypeError, ValueError) as exc:
            raise MaterializationError(f"record_count invalid for {source_id}") from exc
        redistribution = str(entry.get("redistribution_status", ""))
        if not redistribution:
            redistribution = str(manifest.get("redistribution", {}).get("redistribution_status", ""))
        if redistribution not in {"verified_redistributable", "external_link_only", "audit_only", "to_review"}:
            raise MaterializationError(f"invalid redistribution_status for {source_id}: {redistribution}")
        source_rows.append(
            {
                "release_version": release_version,
                "source_id": source_id,
                "publication_id_ref": str(manifest.get("pmid")),
                "assembly_id_ref": str(manifest.get("reference_genome")),
                "species": str(manifest.get("species", "")),
                "phylum": str(manifest.get("phylum", "")) or None,
                "assay_family": str(manifest.get("assay_family", "")),
                "release_status": status,
                "evidence_class": evidence,
                "redistribution_status": redistribution,
                "accessibility_status": str(manifest.get("accessibility_status", "")),
                "coordinate_status": str(manifest.get("coordinate_status", "")),
                "processing_status": str(manifest.get("processing_status", "")),
                "used_for_batter_augmentation": _parse_flag(
                    registry_row.get("used_for_batter_augmentation"), source_id
                ),
                "record_count": record_count,
                "has_jbrowse": bool(entry.get("has_jbrowse", False)),
                "manifest_path": _source_manifest_path(snapshot, source_id),
                "manifest_sha256": _source_manifest_sha(snapshot, source_id),
                "record_root": f"records/{source_id}",
                "source_note": str(manifest.get("blocker_or_note", "")) or None,
                "decision_note": str(manifest.get("decision_note", "")) or None,
                "known_limitations": str(manifest.get("known_limitations", "")) or None,
            }
        )
        for ordinal, accession in enumerate(_raw_accessions(manifest.get("raw_data_accessions")), start=1):
            namespace, alias = _accession_namespace(accession)
            source_accessions.append(
                {
                    "source_id_ref": source_id,
                    "accession_namespace": namespace,
                    "accession": accession,
                    "raw_value": accession,
                    "accession_type": "study",
                    "ordinal": ordinal,
                    "external_url": _accession_url(namespace, accession),
                }
            )
        for row in endpoint_rows_by_source.get(source_id, []):
            sample_id = str(row.get("sample_id", "")).strip()
            if sample_id:
                sample_keys.add((source_id, sample_id))

    source_rows.sort(key=lambda row: row["source_id"])
    source_accessions.sort(key=lambda row: (row["source_id_ref"], row["ordinal"], row["accession"]))
    samples = [
        {
            "source_id_ref": source_id,
            "sample_id": sample_id,
            "sample_label": None,
            "biological_condition": None,
            "replicate_label": None,
            "sample_accession": None,
            "metadata_json": {},
        }
        for source_id, sample_id in sorted(sample_keys)
    ]

    endpoints: list[dict[str, Any]] = []
    endpoint_ids: set[tuple[str, str]] = set()
    for source_id in source_ids:
        for raw_row in endpoint_rows_by_source.get(source_id, []):
            row = {column: raw_row.get(column, "") for column in V02_ENDPOINT_COLUMNS}
            missing = [column for column in V02_ENDPOINT_COLUMNS if column not in raw_row]
            if missing:
                raise MaterializationError(
                    f"endpoint row missing canonical columns for {source_id}: {missing}"
                )
            row["biological_coordinate_1based"] = _int(
                row["biological_coordinate_1based"], "biological_coordinate_1based"
            )
            row["bed_start_0based"] = _int(row["bed_start_0based"], "bed_start_0based")
            row["bed_end_0based"] = _int(row["bed_end_0based"], "bed_end_0based")
            assembly = str(row["reference_assembly"])
            contig = str(row["reference_name"])
            sample_id = str(row["sample_id"])
            end_id = str(row["end_id"])
            key = (source_id, end_id)
            if key in endpoint_ids:
                raise MaterializationError(f"duplicate endpoint natural key: {source_id}/{end_id}")
            endpoint_ids.add(key)
            if (source_id, sample_id) not in sample_keys:
                raise MaterializationError(f"endpoint sample natural key is not materialized: {source_id}/{sample_id}")
            if (assembly, contig) not in endpoint_keys:
                raise MaterializationError(f"endpoint contig natural key is not materialized: {assembly}/{contig}")
            row.update(
                {
                    "release_version": release_version,
                    "source_id_ref": source_id,
                    "contig_id_ref": {"assembly_accession": assembly, "contig_accession": contig},
                    "sample_id_ref": {"source_id": source_id, "sample_id": sample_id},
                    "source_pk_ref": source_id,
                }
            )
            endpoints.append(row)
    endpoints.sort(key=lambda row: (row["source_id_ref"], row["end_id"]))

    annotations = _build_annotations(snapshot, source_ids)
    annotation_end_ids = {(row["source_id_ref"], row["end_id"]) for row in annotations}
    if not annotation_end_ids.issubset(endpoint_ids):
        missing = sorted(annotation_end_ids - endpoint_ids)[:5]
        raise MaterializationError(f"annotation endpoint foreign-key closure failed: {missing}")

    assets: list[dict[str, Any]] = []
    verified_assets = snapshot.get("verified_assets", [])
    declared_files = snapshot.get("declared_files", {})
    verified_lookup = {
        (str(item.get("source_id")), str(item.get("asset_id"))): item
        for item in verified_assets
    }
    for source_id in source_ids:
        entry = entries[source_id]
        status = str(entry.get("release_status", ""))
        redistribution = str(entry.get("redistribution_status", ""))
        for relative, path_value in sorted(declared_files.get(source_id, {}).items()):
            asset_id = "--".join(
                re.sub(r"[^A-Za-z0-9._-]+", "_", value)
                for value in (release_version, source_id, relative)
            )
            item = verified_lookup.get((source_id, asset_id))
            if item is None:
                continue
            logical_path = f"records/{source_id}/{Path(relative).as_posix()}"
            asset_kind = str(item.get("asset_kind", "metadata"))
            assets.append(
                {
                    "asset_id": asset_id,
                    "release_version": release_version,
                    "source_id_ref": source_id,
                    "assembly_id_ref": None,
                    "asset_kind": asset_kind,
                    "logical_path": logical_path,
                    "origin_url": _asset_origin(asset_origin_base, asset_id),
                    "origin_host": urlparse(_asset_origin(asset_origin_base, asset_id)).hostname,
                    "byte_size": int(item.get("byte_size", 0)),
                    "sha256": str(item.get("sha256", "")),
                    "mime_type": _mime_type(logical_path, asset_kind),
                    # The origin is only planned and has not passed an HTTP
                    # 206 audit. Do not infer remote Range support from the
                    # local file or the planned URL.
                    "supports_range": False,
                    "redistribution_status": redistribution,
                    "is_public": bool(status in SOURCE_STATUS_PUBLISHED and redistribution == "verified_redistributable"),
                }
            )
    assets.sort(key=lambda row: row["asset_id"])
    if len(assets) != len(verified_assets):
        raise MaterializationError(
            f"asset closure failed: materialized {len(assets)} but validator verified {len(verified_assets)}"
        )

    tables: dict[str, list[dict[str, Any]]] = {
        "release_versions": [
            {
                "release_version": release_version,
                "release_date": release.get("release_date"),
                "canonical_manifest_path": "release_manifest.json",
                "canonical_manifest_sha256": canonical_sha,
                "status": "validated",
                "is_current": False,
                "created_at": generated_at_utc,
            }
        ],
        "import_runs": [
            {
                "release_version": release_version,
                "importer_name": "bted-materialize",
                "importer_version": MATERIALIZER_VERSION,
                "input_manifest_path": "release_manifest.json",
                "input_manifest_sha256": canonical_sha,
                "staging_location": "deterministic-materialization-bundle",
                "run_status": "validated",
                "started_at": generated_at_utc,
                "finished_at": generated_at_utc,
                "validation_summary": {
                    "canonical_validation_status": "validated",
                    "postgresql_ready": True,
                    "write_mode": "not_written",
                },
                "error_summary": None,
            }
        ],
        "publications": publications,
        "assemblies": assemblies,
        "contigs": contigs,
        "sources": source_rows,
        "source_accessions": source_accessions,
        "samples": samples,
        "endpoints": endpoints,
        "source_annotations": annotations,
        "genes": [],
        "endpoint_gene_context": [],
        "assets": assets,
    }
    return tables


def _atomic_write_bundle(
    output_dir: Path,
    tables: Mapping[str, list[dict[str, Any]]],
    manifest: dict[str, Any],
) -> dict[str, Any]:
    parent = output_dir.parent
    parent.mkdir(parents=True, exist_ok=True)
    if output_dir.exists():
        if not output_dir.is_dir():
            raise MaterializationError(f"output path is not a directory: {output_dir}")
        if any(output_dir.iterdir()):
            raise MaterializationError(f"refusing to overwrite non-empty output directory: {output_dir}")
    temp_dir = Path(tempfile.mkdtemp(prefix=f".{output_dir.name}.tmp-", dir=str(parent)))
    try:
        table_metadata: dict[str, dict[str, Any]] = {}
        for table_name in TABLE_ORDER:
            rows = tables.get(table_name, [])
            file_name = f"{table_name}.jsonl"
            count, digest, byte_size = _write_jsonl(temp_dir / file_name, rows)
            table_metadata[table_name] = {
                "file": file_name,
                "row_count": count,
                "sha256": digest,
                "byte_size": byte_size,
            }
        manifest["tables"] = table_metadata
        manifest_path = temp_dir / "manifest.json"
        manifest_path.write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        checksum_lines: list[str] = []
        for path in sorted(temp_dir.iterdir(), key=lambda item: item.name):
            if path.name == "SHA256SUMS.txt":
                continue
            checksum_lines.append(f"{sha256_file(path)}  {path.name}")
        (temp_dir / "SHA256SUMS.txt").write_text(
            "\n".join(checksum_lines) + "\n", encoding="utf-8"
        )
        # Make the directory durable before the rename when the platform
        # supports fsync on directories; the operation remains harmless on
        # filesystems that do not expose it.
        for path in temp_dir.iterdir():
            with path.open("rb") as handle:
                os.fsync(handle.fileno())
        if output_dir.exists():
            output_dir.rmdir()  # explicitly allowed only for an empty target
        os.replace(temp_dir, output_dir)
        return manifest
    except Exception:
        shutil.rmtree(temp_dir, ignore_errors=True)
        raise


def materialize_release(
    release_root: str | Path = "data/public/v0.2.0",
    *,
    repo_root: str | Path | None = None,
    contig_registry: str | Path | None = None,
    output_dir: str | Path,
    asset_origin_base: str,
    generated_at_utc: str | None = None,
) -> MaterializationResult:
    """Validate and materialize a release into a deterministic JSONL bundle.

    ``output_dir`` and ``asset_origin_base`` are intentionally required.  The
    function never writes a default location or infers a remote asset host.
    ``asset_origin_base`` is only a planned URL prefix; no HTTP request is made
    and no remote object is claimed to exist.
    """

    origin_base, origin_host = _validate_origin_base(asset_origin_base)
    generated_at = _utc_timestamp(generated_at_utc)
    output_path = Path(output_dir).expanduser().resolve()
    validator = CanonicalReleaseValidator(
        release_root,
        repo_root=repo_root,
        contig_registry=contig_registry,
    )
    report = validator.validate()
    if not report.ok:
        raise MaterializationError(
            "canonical validation failed; no materialization performed: "
            + "; ".join(issue.message for issue in report.issues[:5])
        )
    if not report.plan.get("postgresql_ready", False):
        raise MaterializationError("canonical release is validated but not PostgreSQL-ready")
    try:
        snapshot = validator.export_snapshot()
    except (RuntimeError, ValueError) as exc:
        raise MaterializationError(str(exc)) from exc
    tables = _build_tables(snapshot, origin_base, generated_at)
    # Explicit row-count/closure assertions catch a malformed future release
    # before any bundle bytes are exposed.
    source_ids = snapshot["source_ids"]
    expected_sources = int(report.summary.get("source_count", len(source_ids)))
    expected_endpoints = int(report.summary.get("published_record_count", len(tables["endpoints"])))
    expected_assets = int(report.plan.get("tables", {}).get("assets", {}).get("row_count", len(tables["assets"])))
    if len(source_ids) != expected_sources:
        raise MaterializationError(f"source count changed between validation and materialization: {len(source_ids)} != {expected_sources}")
    if len(tables["endpoints"]) != expected_endpoints:
        raise MaterializationError(f"endpoint count changed between validation and materialization: {len(tables['endpoints'])} != {expected_endpoints}")
    if len(tables["assets"]) != expected_assets:
        raise MaterializationError(f"asset count changed between validation and materialization: {len(tables['assets'])} != {expected_assets}")
    if any(row["source_id_ref"] == "BATTER_S1_002" for row in tables["endpoints"]):
        raise MaterializationError("S1_002 must not produce endpoint rows")
    if any(row["source_id_ref"] == "BATTER_S1_002" for row in tables["source_annotations"]):
        raise MaterializationError("S1_002 must not produce annotation rows")
    report_summary = report.summary
    registry_path = Path(str(snapshot["contig_registry_path"]))
    contig_registry_sha = sha256_file(registry_path) if registry_path.is_file() else None
    repo_path = Path(str(snapshot["repo_root"])).resolve()
    try:
        contig_registry_display = registry_path.resolve().relative_to(repo_path).as_posix()
    except ValueError:
        contig_registry_display = registry_path.name
    annotation_field_provenance = _build_annotation_field_provenance(
        snapshot, [str(source_id) for source_id in source_ids]
    )
    manifest = {
        "materialization_schema_version": MATERIALIZATION_SCHEMA_VERSION,
        "materializer_version": MATERIALIZER_VERSION,
        "release_version": report_summary.get("release_version"),
        "generated_at_utc": generated_at,
        "canonical_validation_status": "validated",
        "postgresql_ready": True,
        "write_mode": "not_written",
        "canonical_manifest": {
            "path": "release_manifest.json",
            "sha256": report.plan["canonical_manifest"]["sha256"],
        },
        "contig_registry": {
            "path": contig_registry_display,
            "sha256": contig_registry_sha,
        },
        "asset_origin": {
            "base": origin_base,
            "host": origin_host,
            "asset_origin_status": "planned_not_verified",
        },
        "foreign_key_mode": "natural_key_refs",
        "unresolved": list(report_summary.get("unresolved", [])),
        "source_count": len(tables["sources"]),
        "source_annotation_input_row_count": int(
            report.summary.get("source_annotation_record_count", 0)
        ),
        "source_annotation_materialized_row_count": len(tables["source_annotations"]),
        "annotation_field_provenance": annotation_field_provenance,
        "published_source_count": sum(
            row["release_status"] in SOURCE_STATUS_PUBLISHED for row in tables["sources"]
        ),
        "audit_only_source_ids": [
            row["source_id"] for row in tables["sources"] if row["release_status"] == "audit_only"
        ],
    }
    final_manifest = _atomic_write_bundle(output_path, tables, manifest)
    return MaterializationResult(output_path, final_manifest)


# Alias retained for callers that prefer the language used in the design
# document.  Both names have identical validation and no-write semantics.
build_materialization_bundle = materialize_release
